name: Hugo site CI

on:
  push:
  schedule:
    - cron: '0 6 * * *'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Restore data from data branch
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git fetch origin data || true
        mkdir -p data
        git show origin/data:fftt.json > data/fftt.json 2>/dev/null || true
        git show origin/data:players.json > data/players.json 2>/dev/null || true
        git show origin/data:events.json > data/events.json 2>/dev/null || true
    - name: Build the site in the jekyll/builder container
      env:
        facebook_token: ${{ secrets.facebook_token }}
        fftt_passwd: ${{ secrets.fftt_passwd }}
      run: |
        docker run -v ${{ github.workspace }}:/app -e facebook_token=$facebook_token -e FFTT_PASSWD=$fftt_passwd jhanos/hugo sh /app/generateSite.sh
        curl http://www.fftt.com/mobile/pxml/xml_initialisation.php
    - name: Generate pdf
      run: |
        docker run -v ${{ github.workspace }}:/app --entrypoint=sh pandoc/latex /app/generatePdf.sh
    - name: Commit to repository
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        COMMIT_MSG: |
          chore: update generated data [skip ci]
      run: |
        git config user.email "jhanosl@gmail.com"
        git config user.name "Thomas Langlois"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git add .
        git diff --cached --quiet || git commit -m "${COMMIT_MSG}"
        git subtree split -P data -b data_split
        git push -f origin data_split:data
        git subtree split -P public -b master
        git push -f origin master:master
        git rm -r --cached public/ data/
        git commit --amend --no-edit
        git push origin HEAD:gohugo
