name: Hugo site CI

on:
  push:
  schedule:
    - cron: '0 6 * * *'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the site in the jekyll/builder container
      env:
        facebook_token: ${{ secrets.facebook_token }}
      run: |
        docker run -v ${{ github.workspace }}:/app -e facebook_token=$facebook_token jhanos/hugo sh /facebook.sh
        docker run -v ${{ github.workspace }}:/app jhanos/hugo
    - name: Commit to repository
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        COMMIT_MSG: |
          commit by github actions
          skip-checks: true
      run: |
        git config user.email "jhanosl@gmail.com"
        git config user.name "Thomas Langlois"
        # Update origin with token
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        # Checkout the branch so we can push back to it
        git add .
        # Only commit and push if we have changes
        git commit -m "${COMMIT_MSG}"
        git subtree split -P public -b master
        git push -f origin master:master
