name: Hugo site CI

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/app -v ${{ github.workspace }}/_site:/app/public \
        jhanos/hugo
